# Generated by Django 6.0.4 on 2026-08-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('In', 'Income'), ('Ex', 'Expense')], default='Ex', max_length=3),
            preserve_default=False,
        ),
    ]
